### ISSUE TITLE
Logo should be clickable back to grommet.io

### ISSUE THREAD

**Issue by djksar** [grommet/grommet-blog#44]
The Grommet logo should be clickable to grommet.io.

**Comment by alansouzati** [comment]
Let me run that with Bryan, for me it is kind of weird to have the icon go somewhere and the Blog text to go back to the homepage.

**Comment by djksar** [comment]
sounds good. that is how we designed it originally but open to suggestions. totally minor. just need a way to get back to the home page - grommet.io

**Comment by alansouzati** [comment]
talking with you guys (Chris, Bryan and Randy), it seems that we all agree that we can keep the way it is right now.

We can't guarantee that users will come from the grommet.io page. For example, if the user clicks in a twitter post and wants to read more blog items, he will eventually click in the grommet logo and instead of going in the blog home page, he will be in the grommet.io home page.
